=== cyrilou242/learning-lightnr/app/pywsd/data/semeval2007_coarse_grain_wsd/coarse-all-words.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>
<!ELEMENT corpus (text+)>
<!ATTLIST corpus lang CDATA #REQUIRED>

<!ELEMENT text (sentence+)>
<!ATTLIST text id ID #REQUIRED>

<!ELEMENT sentence (#PCDATA | instance)*>
<!ATTLIST sentence id ID #REQUIRED>

<!ELEMENT instance (#PCDATA)>
<!ATTLIST instance id ID #REQUIRED>
<!ATTLIST instance lemma CDATA #REQUIRED>
<!ATTLIST instance pos (a|n|v|r) #REQUIRED>

=== cyrilou242/learning-lightnr/app/pywsd/data/semeval2007_coarse_grain_wsd/eng-coarse-all-words.xml
<?xml version="1.0" encoding="utf8" ?>
<!DOCTYPE corpus SYSTEM "coarse-all-words.dtd">
<corpus lang="en">
<text id="d001">
<sentence id="d001.s001">
Your
Oct
.
6
<instance id="d001.s001.t001" lemma="editorial" pos="n">editorial</instance>
``
The
<instance id="d001.s001.t002" lemma="Ill" pos="a">Ill</instance>
<instance id="d001.s001.t003" lemma="Homeless" pos="n">Homeless</instance>
''
<instance id="d001.s001.t004" lemma="refer" pos="v">referred</instance>
to
<instance id="d001.s001.t005" lemma="research" pos="n">research</instance>
by
us
and
<instance id="d001.s001.t006" lemma="six" pos="a">six</instance>
of
our
<instance id="d001.s001.t007" lemma="colleague" pos="n">colleagues</instance>
that
was
<instance id="d001.s001.t008" lemma="report" pos="v">reported</instance>
in
the
Sept
.
8
<instance id="d001.s001.t009" lemma="issue" pos="n">issue</instance>
of
the
Journal
of
the
American
Medical
Association
.
</sentence>
<sentence id="d001.s002">
Your
<instance id="d001.s002.t001" lemma="comment" pos="n">comments</instance>
<instance id="d001.s002.t002" lemma="imply" pos="v">implied</instance>
we
had
<instance id="d001.s002.t003" lemma="discover" pos="v">discovered</instance>
that
the
``
<instance id="d001.s002.t004" lemma="principal" pos="a">principal</instance>
<instance id="d001.s002.t005" lemma="cause" pos="n">cause</instance>
''
of
<instance id="d001.s002.t006" lemma="homelessness" pos="n">homelessness</instance>
<instance id="d001.s002.t007" lemma="be" pos="v">is</instance>
to
be
<instance id="d001.s002.t008" lemma="find" pos="v">found</instance>
in
the
<instance id="d001.s002.t009" lemma="large" pos="a">large</instance>
<instance id="d001.s002.t010" lemma="number" pos="n">numbers</instance>
of
<instance id="d001.s002.t011" lemma="mentally" pos="r">mentally</instance>
<instance id="d001.s002.t012" lemma="ill" pos="a">ill</instance>
and
substance-abusing
<instance id="d001.s002.t013" lemma="people" pos="n">people</instance>
in
the
<instance id="d001.s002.t014" lemma="homeless" pos="a">homeless</instance>
<instance id="d001.s002.t015" lemma="population" pos="n">population</instance>
.
</sentence>
<sentence id="d001.s003">
We
have
<instance id="d001.s003.t001" lemma="make" pos="v">made</instance>
no
such
<instance id="d001.s003.t002" lemma="statement" pos="n">statement</instance>
.
</sentence>
<sentence id="d001.s004">
It
is
<instance id="d001.s004.t001" lemma="clear" pos="a">clear</instance>
that
most
<instance id="d001.s004.t002" lemma="mentally" pos="r">mentally</instance>
<instance id="d001.s004.t003" lemma="ill" pos="a">ill</instance>
<instance id="d001.s004.t004" lemma="people" pos="n">people</instance>
and
most
<instance id="d001.s004.t005" lemma="alcoholic" pos="n">alcoholics</instance>
do
not
<instance id="d001.s004.t006" lemma="become" pos="v">become</instance>
<instance id="d001.s004.t007" lemma="homeless" pos="a">homeless</instance>
.
</sentence>
<sentence id="d001.s005">
The
``
<instance id="d001.s005.t001" lemma="cause" pos="n">causes</instance>
''
of
<instance id="d001.s005.t002" lemma="homelessness" pos="n">homelessness</instance>
are
<instance id="d001.s005.t003" lemma="poorly" pos="r">poorly</instance>
<instance id="d001.s005.t004" lemma="understand" pos="v">understood</instance>
and
<instance id="d001.s005.t005" lemma="complex" pos="a">complex</instance>
in
any
<instance id="d001.s005.t006" lemma="individual" pos="a">individual</instance>
<instance id="d001.s005.t007" lemma="case" pos="n">case</instance>
.
</sentence>
<sentence id="d001.s006">
In
<instance id="d001.s006.t001" lemma="quote" pos="v">quoting</instance>
from
our
<instance id="d001.s006.t002" lemma="research" pos="n">research</instance>
you
<instance id="d001.s006.t003" lemma="emphasize" pos="v">emphasized</instance>
the
<instance id="d001.s006.t004" lemma="high" pos="a">high</instance>
<instance id="d001.s006.t005" lemma="prevalence" pos="n">prevalence</instance>
of
<instance id="d001.s006.t006" lemma="mental" pos="a">mental</instance>
<instance id="d001.s006.t007" lemma="illness" pos="n">illness</instance>
and
<instance id="d001.s006.t008" lemma="alcoholism" pos="n">alcoholism</instance>
.
</sentence>
<sentence id="d001.s007">
You
did
not
<instance id="d001.s007.t001" lemma="note" pos="v">note</instance>
that
the
<instance id="d001.s007.t002" lemma="homeless" pos="a">homeless</instance>
<instance id="d001.s007.t003" lemma="people" pos="n">people</instance>
we
<instance id="d001.s007.t004" lemma="examine" pos="v">examined</instance>
<instance id="d001.s007.t005" lemma="have" pos="v">had</instance>
a
<instance id="d001.s007.t006" lemma="multitude" pos="n">multitude</instance>
of
<instance id="d001.s007.t007" lemma="physical" pos="a">physical</instance>
<instance id="d001.s007.t008" lemma="disorder" pos="n">disorders</instance>
<instance id="d001.s007.t009" lemma="in_addition" pos="r">in addition</instance>
to
their
<instance id="d001.s007.t010" lemma="psychiatric" pos="a">psychiatric</instance>
<instance id="d001.s007.t011" lemma="problem" pos="n">problems</instance>
and
<instance id="d001.s007.t012" lemma="substance_abuse" pos="n">substance abuse</instance>
.
</sentence>
<sentence id="d001.s008">
They
<instance id="d001.s008.t001" lemma="suffer" pos="v">suffered</instance>
from
<instance id="d001.s008.t002" lemma="malnutrition" pos="n">malnutrition</instance>
,
<instance id="d001.s008.t003" lemma="chest" pos="n">chest</instance>
<instance id="d001.s008.t004" lemma="disease" pos="n">diseases</instance>
,
<instance id="d001.s008.t005" lemma="cardiovascular" pos="a">cardiovascular</instance>
<instance id="d001.s008.t006" lemma="disorder" pos="n">disorders</instance>
,
<instance id="d001.s008.t007" lemma="skin" pos="n">skin</instance>
<instance id="d001.s008.t008" lemma="problem" pos="n">problems</instance>
,
<instance id="d001.s008.t009" lemma="infectious" pos="a">infectious</instance>
<instance id="d001.s008.t010" lemma="disease" pos="n">diseases</instance>
and
the
<instance id="d001.s008.t011" lemma="aftereffect" pos="n">aftereffects</instance>
of
<instance id="d001.s008.t012" lemma="assault" pos="n">assaults</instance>
and
<instance id="d001.s008.t013" lemma="rape" pos="n">rape</instance>
.
</sentence>
<sentence id="d001.s009">
<instance id="d001.s009.t001" lemma="Homeless" pos="a">Homeless</instance>
<instance id="d001.s009.t002" lemma="people" pos="n">people</instance>
not
only
<instance id="d001.s009.t003" lemma="lack" pos="v">lack</instance>
<instance id="d001.s009.t004" lemma="safety" pos="n">safety</instance>
,
<instance id="d001.s009.t005" lemma="privacy" pos="n">privacy</instance>
and
<instance id="d001.s009.t006" lemma="shelter" pos="n">shelter</instance>
,
they
<instance id="d001.s009.t007" lemma="also" pos="r">also</instance>
<instance id="d001.s009.t008" lemma="lack" pos="v">lack</instance>
the
<instance id="d001.s009.t009" lemma="elementary" pos="a">elementary</instance>
<instance id="d001.s009.t010" lemma="necessity" pos="n">necessities</instance>
of
<instance id="d001.s009.t011" lemma="nutrition" pos="n">nutrition</instance>
,
cleanliness
and
<instance id="d001.s009.t012" lemma="basic" pos="a">basic</instance>
<instance id="d001.s009.t013" lemma="health_care" pos="n">health care</instance>
.
</sentence>
<sentence id="d001.s010">
In
a
<instance id="d001.s010.t001" lemma="recent" pos="a">recent</instance>
<instance id="d001.s010.t002" lemma="report" pos="n">report</instance>
,
the
Institute
of
Medicine
<instance id="d001.s010.t003" lemma="point_out" pos="v">pointed out</instance>
that
<instance id="d001.s010.t004" lemma="certain" pos="a">certain</instance>
<instance id="d001.s010.t005" lemma="health" pos="n">health</instance>
<instance id="d001.s010.t006" lemma="problem" pos="n">problems</instance>
may
<instance id="d001.s010.t007" lemma="predispose" pos="v">predispose</instance>
a
<instance id="d001.s010.t008" lemma="person" pos="n">person</instance>
to
<instance id="d001.s010.t009" lemma="homelessness" pos="n">homelessness</instance>
,
others
may
<instance id="d001.s010.t010" lemma="be" pos="v">be</instance>
a
<instance id="d001.s010.t011" lemma="consequence" pos="n">consequence</instance>
of
it
,
and
a
<instance id="d001.s010.t012" lemma="third" pos="a">third</instance>
<instance id="d001.s010.t013" lemma="category" pos="n">category</instance>
is
<instance id="d001.s010.t014" lemma="compose" pos="v">composed</instance>
of
<instance id="d001.s010.t015" lemma="disorder" pos="n">disorders</instance>
whose
<instance id="d001.s010.t016" lemma="treatment" pos="n">treatment</instance>
<instance id="d001.s010.t017" lemma="be" pos="v">is</instance>
<instance id="d001.s010.t018" lemma="difficult" pos="a">difficult</instance>
or
<instance id="d001.s010.t019" lemma="impossible" pos="a">impossible</instance>
if
a
<instance id="d001.s010.t020" lemma="person" pos="n">person</instance>
<instance id="d001.s010.t021" lemma="lack" pos="v">lacks</instance>
<instance id="d001.s010.t022" lemma="adequate" pos="a">adequate</instance>
<instance id="d001.s010.t023" lemma="shelter" pos="n">shelter</instance>
.
</sentence>
<sentence id="d001.s011">
The
<instance id="d001.s011.t001" lemma="interaction" pos="n">interactions</instance>
between
<instance id="d001.s011.t002" lemma="health" pos="n">health</instance>
and
<instance id="d001.s011.t003" lemma="homelessness" pos="n">homelessness</instance>
<instance id="d001.s011.t004" lemma="be" pos="v">are</instance>
<instance id="d001.s011.t005" lemma="complex" pos="a">complex</instance>
,
<instance id="d001.s011.t006" lemma="defy" pos="v">defying</instance>
<instance id="d001.s011.t007" lemma="sweeping" pos="a">sweeping</instance>
<instance id="d001.s011.t008" lemma="generalization" pos="n">generalizations</instance>
as
to
``
<instance id="d001.s011.t009" lemma="cause" pos="n">cause</instance>
''
or
``
<instance id="d001.s011.t010" lemma="effect" pos="n">effect</instance>
.
''
</sentence>
<sentence id="d001.s012">
If
we
<instance id="d001.s012.t001" lemma="look" pos="v">look</instance>
to
the
